// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Oleksii PELYKH

// Types (profile, messaging, instance, account, campaign — CDP types are internal)
export type {
  Account,
  ActionConfig,
  ActionErrorSummary,
  ActionPeopleCounts,
  ActionStatistics,
  CampaignActionConfig,
  CampaignActionResult,
  ActionSettings,
  ActionTargetPerson,
  Campaign,
  CampaignAction,
  CampaignConfig,
  CampaignPersonEntry,
  CampaignPersonState,
  CampaignRunResult,
  CampaignState,
  ResultProfileData,
  CampaignStatistics,
  CampaignStatus,
  CampaignSummary,
  CampaignUpdateConfig,
  CriticalErrorIssueData,
  DialogIssueData,
  ExcludeListEntry,
  Chat,
  ChatParticipant,
  ConversationMessages,
  ConversationThread,
  CurrentPosition,
  Education,
  ExternalId,
  ExternalIdTypeGroup,
  GetResultsOptions,
  GetStatisticsOptions,
  ImportPeopleResult,
  InstanceInfo,
  InstanceIssue,
  InstanceStatus,
  ListCampaignPeopleOptions,
  ListCampaignsOptions,
  Message,
  MessageStats,
  MessageSummary,
  MiniProfile,
  PopupState,
  Position,
  Profile,
  ProfileFindOptions,
  ProfileSearchOptions,
  ProfileSearchResult,
  ProfileSummary,
  RunnerState,
  Skill,
  StartInstanceParams,
  StartInstanceResult,
  UIHealthStatus,
} from "./types/index.js";

// Services
export {
  AccountResolutionError,
  ActionExecutionError,
  type ActionResult,
  AppLaunchError,
  AppNotFoundError,
  AppService,
  type AppServiceOptions,
  CampaignExecutionError,
  CampaignService,
  CampaignTimeoutError,
  type DatabaseContext,
  ExtractionTimeoutError,
  type InstanceDatabaseContext,
  InstanceNotRunningError,
  InstanceService,
  InvalidProfileUrlError,
  LauncherService,
  LinkedHelperNotRunningError,
  resolveAccount,
  ServiceError,
  StartInstanceError,
  startInstanceWithRecovery,
  UIBlockedError,
  type StartInstanceOutcome,
  checkStatus,
  type AccountInstanceStatus,
  type DatabaseStatus,
  type LauncherStatus,
  type StatusReport,
  waitForInstancePort,
  waitForInstanceShutdown,
  withDatabase,
  withInstanceDatabase,
  WrongPortError,
} from "./services/index.js";

// Data access
export {
  CampaignExcludeListRepository,
  CampaignRepository,
  CampaignStatisticsRepository,
  DatabaseClient,
  type DatabaseClientOptions,
  discoverAllDatabases,
  discoverDatabase,
  MessageRepository,
  ProfileRepository,
} from "./db/index.js";

// Formats
export {
  CampaignFormatError,
  FormatError,
  parseCampaignJson,
  parseCampaignYaml,
  serializeCampaignJson,
  serializeCampaignYaml,
} from "./formats/index.js";

// Data (action types catalog)
export {
  type ActionCategory,
  type ActionType,
  type ActionTypeCatalog,
  type ActionTypeInfo,
  type ConfigFieldSchema,
  getActionTypeCatalog,
  getActionTypeInfo,
} from "./data/index.js";

// Errors (DB + CDP errors can propagate through the service layer)
export {
  ActionNotFoundError,
  CampaignNotFoundError,
  ChatNotFoundError,
  DatabaseError,
  DatabaseNotFoundError,
  ExcludeListNotFoundError,
  NoNextActionError,
  ProfileNotFoundError,
} from "./db/index.js";

export {
  CDPConnectionError,
  CDPError,
  CDPEvaluationError,
  CDPTimeoutError,
  discoverInstancePort,
  discoverTargets,
  findApp,
  type DiscoveredApp,
  killInstanceProcesses,
} from "./cdp/index.js";

// Operations (shared business logic for CLI + MCP)
export {
  type ConnectionOptions,
  // Campaign CRUD
  campaignGet,
  type CampaignGetInput,
  type CampaignGetOutput,
  campaignList,
  type CampaignListInput,
  type CampaignListOutput,
  campaignCreate,
  type CampaignCreateInput,
  type CampaignCreateOutput,
  campaignUpdate,
  type CampaignUpdateInput,
  type CampaignUpdateOutput,
  campaignDelete,
  type CampaignDeleteInput,
  type CampaignDeleteOutput,
  // Campaign people
  campaignListPeople,
  type CampaignListPeopleInput,
  type CampaignListPeopleOutput,
  // Campaign execution
  campaignStart,
  type CampaignStartInput,
  type CampaignStartOutput,
  campaignStop,
  type CampaignStopInput,
  type CampaignStopOutput,
  campaignRetry,
  type CampaignRetryInput,
  type CampaignRetryOutput,
  campaignMoveNext,
  type CampaignMoveNextInput,
  type CampaignMoveNextOutput,
  campaignStatistics,
  type CampaignStatisticsInput,
  type CampaignStatisticsOutput,
  campaignStatus,
  type CampaignStatusInput,
  type CampaignStatusOutput,
  // Campaign configuration
  campaignAddAction,
  type CampaignAddActionInput,
  type CampaignAddActionOutput,
  campaignRemoveAction,
  type CampaignRemoveActionInput,
  type CampaignRemoveActionOutput,
  campaignReorderActions,
  type CampaignReorderActionsInput,
  type CampaignReorderActionsOutput,
  campaignExport,
  type CampaignExportInput,
  type CampaignExportOutput,
  // Exclude list
  campaignExcludeAdd,
  type CampaignExcludeAddInput,
  type CampaignExcludeAddOutput,
  campaignExcludeRemove,
  type CampaignExcludeRemoveInput,
  type CampaignExcludeRemoveOutput,
  campaignExcludeList,
  type CampaignExcludeListInput,
  type CampaignExcludeListOutput,
  // Error detection
  getErrors,
  type GetErrorsInput,
  type GetErrorsOutput,
  // Messaging
  queryMessages,
  type QueryMessagesInput,
  type QueryMessagesOutput,
  checkReplies,
  type CheckRepliesInput,
  type CheckRepliesOutput,
  scrapeMessagingHistory,
  type ScrapeMessagingHistoryInput,
  type ScrapeMessagingHistoryOutput,
  importPeopleFromUrls,
  type ImportPeopleFromUrlsInput,
  type ImportPeopleFromUrlsOutput,
} from "./operations/index.js";

// Constants
export { DEFAULT_CDP_PORT } from "./constants.js";

// Utilities
export { delay, errorMessage, isCdpPort, isLoopbackAddress } from "./utils/index.js";
